export const SOLANA_CHAIN_ID = 1151111081099710;

export const SOLANA_TOKENS = [
  {
    symbol: "SOL",
    name: "Solana",
    decimals: 9,
    contractAddress: "11111111111111111111111111111111",
    logoUrl: "/chains/solana/sol.png",
    chainId: SOLANA_CHAIN_ID,
  },
  {
    symbol: "USDC",
    name: "USD Coin",
    decimals: 6,
    contractAddress: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    logoUrl: "/chains/solana/usdc.png",
    chainId: SOLANA_CHAIN_ID,
  },
  {
    symbol: "USDT",
    name: "Tether USD",
    decimals: 6,
    contractAddress: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
    logoUrl: "/chains/solana/usdt.png",
    chainId: SOLANA_CHAIN_ID,
  },
  {
    symbol: "RAY",
    name: "Raydium",
    decimals: 6,
    contractAddress: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
    logoUrl: "/chains/solana/ray.png",
    chainId: SOLANA_CHAIN_ID,
  },
  {
    symbol: "BONK",
    name: "Bonk",
    decimals: 5,
    contractAddress: "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",
    logoUrl: "/chains/solana/bonk.png",
    chainId: SOLANA_CHAIN_ID,
  },
  {
    symbol: "JUP",
    name: "Jupiter",
    decimals: 6,
    contractAddress: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
    logoUrl: "/chains/solana/jup.png",
    chainId: SOLANA_CHAIN_ID,
  },
  {
    symbol: "WIF",
    name: "dogwifhat",
    decimals: 6,
    contractAddress: "EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm",
    logoUrl: "/chains/solana/wif.png",
    chainId: SOLANA_CHAIN_ID,
  },
  {
    symbol: "PYTH",
    name: "Pyth Network",
    decimals: 6,
    contractAddress: "HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3",
    logoUrl: "/chains/solana/pyth.png",
    chainId: SOLANA_CHAIN_ID,
  },
];
